/* eslint-disable import/prefer-default-export */
export enum Town {
  AMK = 'Ang Mo Kio',
  BDK = 'Bedok',
  BSH = 'Bishan',
  BBT = 'Bukit Batok',
  BKM = 'Bukit Merah',
  BKP = 'Bukit Panjang',
  BKT = 'Bukit Timah',
  CEN = 'Central Area',
  CCK = 'Choa Chu Kang',
  CLE = 'Clementi',
  GEY = 'Geylang',
  HGN = 'Hougang',
  JRE = 'Jurong East',
  JRW = 'Jurong West',
  KAL = 'Kallang/Whampoa',
  LCK = 'Lim Chu Kang',
  MPR = 'Marine Parade',
  PSR = 'Pasir Ris',
  PGL = 'Punggol',
  QUE = 'Queenstown',
  SBW = 'Sembawang',
  SKG = 'Sengkang',
  SER = 'Serangoon',
  TAM = 'Tampines',
  TGH = 'Tengah',
  TAP = 'Toa Payoh',
  WDL = 'Woodlands',
  YIS = 'Yishun',
}

export enum Region {
  Central = 'Central',
  East = 'East',
  North = 'North',
  NorthEast = 'North East',
  West = 'West',
}
